# Generated by Django 2.1.15 on 2020-10-18 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks_consumer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(help_text='the command that triggers function, like /sk8', max_length=100)),
                ('function', models.CharField(help_text='function name that is triggered', max_length=100)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhooks_consumer.Bot')),
            ],
        ),
    ]
