# Generated by Django 2.1.15 on 2020-10-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks_consumer', '0002_botaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
