# Generated by Django 2.1.15 on 2020-10-18 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks_consumer', '0003_bot_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('channel_id', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('chat_id', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='bot',
            name='telegram_channel_id',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='telegram_chat_id',
        ),
        migrations.AddField(
            model_name='bot',
            name='telegram_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webhooks_consumer.TelegramChannel'),
        ),
        migrations.AddField(
            model_name='bot',
            name='telegram_chats',
            field=models.ManyToManyField(help_text='Chats which can trigger this bot', to='webhooks_consumer.TelegramChat'),
        ),
    ]
