# Generated by Django 2.1.15 on 2020-10-18 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks_consumer', '0004_auto_20201018_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchat',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_bot', to='webhooks_consumer.Bot'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='telegram_chats',
            field=models.ManyToManyField(help_text='Chats which can trigger this bot', related_name='chats', to='webhooks_consumer.TelegramChat'),
        ),
    ]
