# Generated by Django 2.1.15 on 2020-10-19 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks_consumer', '0005_auto_20201018_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_function', models.CharField(choices=[('doggo', 'doggo'), ('kitty', 'kitty'), ('fox', 'fox'), ('compliment', 'compliment'), ('insult', 'insult'), ('taco', 'taco'), ('broadcast_message', 'broadcast_message')], help_text='Function that gets text or image that will be sent somewhere', max_length=10)),
                ('output_type', models.CharField(choices=[('IMG', 'IMG'), ('TXT', 'TXT')], help_text='Image url or text', max_length=10)),
                ('output_platform', models.CharField(choices=[('TLGRM', 'Telegram'), ('SLCK', 'Slack')], help_text='Telegram, Slack, etc', max_length=10)),
                ('output_channel', models.ForeignKey(blank=True, help_text='Where the output goes. If None, will go to source', null=True, on_delete=django.db.models.deletion.CASCADE, to='webhooks_consumer.TelegramChannel')),
            ],
        ),
        migrations.RemoveField(
            model_name='bot',
            name='telegram_chats',
        ),
        migrations.RemoveField(
            model_name='botaction',
            name='function',
        ),
        migrations.AlterField(
            model_name='botaction',
            name='bot',
            field=models.ForeignKey(help_text='The Bot that listens to this command and execites this action', on_delete=django.db.models.deletion.CASCADE, to='webhooks_consumer.Bot'),
        ),
        migrations.AlterField(
            model_name='telegramchat',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_chat', to='webhooks_consumer.Bot'),
        ),
        migrations.AddField(
            model_name='botaction',
            name='output',
            field=models.ManyToManyField(to='webhooks_consumer.BotOutput'),
        ),
    ]
