# Generated by Django 2.1.15 on 2020-10-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks_consumer', '0007_auto_20201019_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botoutput',
            name='output_function',
            field=models.CharField(choices=[('doggo', 'doggo'), ('kitty', 'kitty'), ('pet', 'pet'), ('fox', 'fox'), ('compliment', 'compliment'), ('insult', 'insult'), ('taco', 'taco'), ('broadcast_message', 'broadcast_message')], help_text='Function that gets text or image that will be sent somewhere', max_length=20),
        ),
    ]
