# Generated by Django 2.1.15 on 2020-10-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks_consumer', '0008_auto_20201019_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botoutput',
            name='output_type',
        ),
    ]
