# Generated by Django 2.1.15 on 2020-10-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks_consumer', '0009_remove_botoutput_output_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='botaction',
            name='input_platform',
            field=models.CharField(choices=[('TLGRM', 'Telegram'), ('SLCK', 'Slack')], default='TLGRM', help_text='Telegram, Slack, etc', max_length=10),
        ),
    ]
