# Generated by Django 2.1.15 on 2020-10-20 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks_consumer', '0010_botaction_input_platform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelegramChat',
            new_name='InputSource',
        ),
    ]
