# Generated by Django 2.1.15 on 2020-10-20 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks_consumer', '0011_auto_20201020_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputsource',
            name='platform',
            field=models.CharField(choices=[('TLGRM', 'Telegram'), ('SLCK', 'Slack')], default='TLGRM', help_text='Telegram, Slack, etc', max_length=10),
        ),
        migrations.AlterField(
            model_name='inputsource',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listens_to', to='webhooks_consumer.Bot'),
        ),
        migrations.AlterField(
            model_name='inputsource',
            name='chat_id',
            field=models.CharField(db_index=True, help_text='Might be Telegram group chat_id, might be Slack team_id', max_length=100),
        ),
    ]
