# Generated by Django 2.1.15 on 2020-10-20 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks_consumer', '0012_auto_20201020_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='slack_team_id',
        ),
    ]
