# Generated by Django 2.1.15 on 2020-10-20 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks_consumer', '0013_remove_bot_slack_team_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('channel_id', models.CharField(db_index=True, max_length=100)),
                ('platform', models.CharField(choices=[('TLGRM', 'Telegram'), ('SLCK', 'Slack')], default='TLGRM', help_text='Telegram, Slack, etc', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='botoutput',
            name='output_channel',
            field=models.ForeignKey(blank=True, help_text='Where the output goes. If None, will go to source', null=True, on_delete=django.db.models.deletion.CASCADE, to='webhooks_consumer.OutputChannel'),
        ),
    ]
