# Generated by Django 2.1.15 on 2020-10-20 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks_consumer', '0014_auto_20201020_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='slack_channel_name',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='telegram_channel',
        ),
        migrations.RemoveField(
            model_name='botoutput',
            name='output_slack_channel',
        ),
        migrations.RemoveField(
            model_name='botoutput',
            name='output_telegram_channel',
        ),
        migrations.AddField(
            model_name='botaction',
            name='input_source',
            field=models.ForeignKey(help_text='The souce of this action, such as a telegrm chat group', null=True, on_delete=django.db.models.deletion.CASCADE, to='webhooks_consumer.InputSource'),
        ),
        migrations.AlterField(
            model_name='botaction',
            name='bot',
            field=models.ForeignKey(help_text='The Bot that listens to this command and executes this action', on_delete=django.db.models.deletion.CASCADE, to='webhooks_consumer.Bot'),
        ),
        migrations.DeleteModel(
            name='TelegramChannel',
        ),
    ]
