# Generated by Django 2.1.15 on 2020-10-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks_consumer', '0015_auto_20201020_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botaction',
            name='bot',
        ),
        migrations.RemoveField(
            model_name='botaction',
            name='input_platform',
        ),
        migrations.RemoveField(
            model_name='botaction',
            name='input_source',
        ),
        migrations.RemoveField(
            model_name='inputsource',
            name='bot',
        ),
        migrations.AddField(
            model_name='inputsource',
            name='actions',
            field=models.ManyToManyField(blank=True, to='webhooks_consumer.BotAction'),
        ),
    ]
