# Generated by Django 2.1.15 on 2020-10-20 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks_consumer', '0016_auto_20201020_1338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bot',
        ),
    ]
