# Generated by Django 2.1.15 on 2020-10-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks_consumer', '0017_delete_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='botaction',
            name='content_required',
            field=models.BooleanField(default=False, help_text='Does the message require content? EG sk8 True, doggo False'),
        ),
    ]
