# Generated by Django 2.1.15 on 2020-12-22 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks_consumer', '0018_botaction_content_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_notes', models.CharField(help_text='Notes on why this person was blocked.', max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('output_channel', models.ForeignKey(blank=True, help_text='Where the output goes. If None, will go to source', null=True, on_delete=django.db.models.deletion.CASCADE, to='webhooks_consumer.OutputChannel')),
            ],
        ),
    ]
