# Generated by Django 2.1.15 on 2020-12-22 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks_consumer', '0019_blockeduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockeduser',
            name='output_channel',
        ),
        migrations.AddField(
            model_name='blockeduser',
            name='inputsource',
            field=models.ForeignKey(blank=True, help_text='Where the user is blocked from', null=True, on_delete=django.db.models.deletion.CASCADE, to='webhooks_consumer.InputSource'),
        ),
    ]
