# Generated by Django 2.1.15 on 2020-12-30 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks_consumer', '0020_auto_20201222_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockeduser',
            name='inputsource',
        ),
        migrations.DeleteModel(
            name='BlockedUser',
        ),
    ]
