# Generated by Django 2.1.15 on 2021-04-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks_consumer', '0021_auto_20201230_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputsource',
            name='nickname_public',
            field=models.CharField(blank=True, help_text="nickname for bulletins. ex: 'nic on BSC', with BSC insread of Telegram", max_length=10, null=True),
        ),
    ]
