# Generated by Django 2.1.15 on 2021-04-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks_consumer', '0023_auto_20210418_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botoutput',
            name='output_function',
            field=models.CharField(choices=[('doggo', 'doggo'), ('kitty', 'kitty'), ('pet', 'pet'), ('fox', 'fox'), ('compliment', 'compliment'), ('insult', 'insult'), ('taco', 'taco'), ('broadcast_message', 'broadcast_message'), ('duck', 'duck'), ('sloth', 'sloth')], help_text='Function that gets text or image that will be sent somewhere', max_length=20),
        ),
    ]
