# Generated by Django 2.1.15 on 2022-07-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks_consumer', '0024_auto_20210418_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputsource',
            name='enviro',
            field=models.CharField(choices=[('D', 'Develpment'), ('P', 'Production')], default='D', help_text='Environment. Example: Development or Production?', max_length=1),
        ),
        migrations.AddField(
            model_name='outputchannel',
            name='enviro',
            field=models.CharField(choices=[('D', 'Develpment'), ('P', 'Production')], default='D', help_text='Environment. Example: Development or Production?', max_length=1),
        ),
        migrations.AlterField(
            model_name='botoutput',
            name='output_function',
            field=models.CharField(choices=[('doggo', 'doggo'), ('kitty', 'kitty'), ('pet', 'pet'), ('fox', 'fox'), ('compliment', 'compliment'), ('insult', 'insult'), ('taco', 'taco'), ('broadcast_message', 'broadcast_message'), ('duck', 'duck'), ('sloth', 'sloth'), ('bootie', 'bootie')], help_text='Function that gets text or image that will be sent somewhere', max_length=20),
        ),
    ]
